schema_version: 1

context:
  version: 1.1.0

package:
  name: prexsyn-engine
  version: ${{ version }}

source:
  url: https://github.com/luost26/prexsyn-engine/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a6bd8349c2705e80a194f104d863fb9005df427a370690016eb030bcbf2192e3

build:
  skip:
    - not linux
    - match(python, "<3.10")
  number: 0
  script: |
    CMAKE_ARGS="-G Ninja -DCMAKE_CXX_COMPILER=${CXX} -DUSE_SYSTEM_BOOST=ON ${CMAKE_ARGS}"
    ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - python
    - scikit-build-core
    - pip
    - libboost-devel
  run:
    - python

tests:
  - python:
      imports:
        - prexsyn_engine
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/luost26/prexsyn-engine
  repository: https://github.com/luost26/prexsyn-engine
  documentation: https://prexsyn.readthedocs.io/
  summary: 'C++ backend library for PrexSyn with Python bindings'

extra:
  recipe-maintainers:
    - luost26
